name: Terraform CI
on:
  workflow_call:

jobs:
  terraform:
    name: "Terraform build/integrate"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    defaults:
      run:
        working-directory: ./src/InfrastructureAsCode

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          client-secret: ${{ secrets.ARM_CLIENT_SECRET }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}          
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          allow-no-subscriptions: true
          enable-AzPSSession: true
          enable-AzCli: true
          environment: 'AzureCloud'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.4

      - name: Terrformm init
        run: terraform init -no-color

      - name: Terrform validate
        id: validate
        run: terraform validate -no-color
