name: Terraform CI
on:
  workflow_call:

permissions: read-all

jobs:
  terraform:
    name: "Terraform build/integrate"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    defaults:
      run:
        working-directory: ./src/InfrastructureAsCode

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}          
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          auth-type: SERVICE_PRINCIPAL

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.4

      - name: Terrformm init
        run: terraform init -no-color

      - name: Terrform validate
        id: validate
        run: terraform validate -no-color
